# espanso configuration file
# yearluk
# 2020-05-20

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Simple text replacement
  - trigger: ":espanso "
    replace: "Hi there!"

  - trigger: ":br"
    replace: "Best regards,\n\nStephen\n07944.683.642 "

  # Get ISO date
  - trigger: ":isod "
    replace: "{{isodate}}"
    vars:
      - name: isodate
        type: date
        params:
          format: "%Y-%m-%d "

# Get ISO date-time
  - trigger: ":isodt "
    replace: "{{isodatetime}} "
    vars:
      - name: isodatetime
        type: date
        params:
          format: "%Y-%m-%dT%H:%M:%S "

# Time in 0H:0M
  - trigger: ":time "
    replace: "{{time}} "
    vars:
      - name: time
        type: date
        params:
          format: "%R "

  # UNIX time ... handy for unique ids
  - trigger: ":utime "
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "date '+%s'"

  # md5 hash of UNIX time for unique ids
  - trigger: ":hashid "
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "md5 -s `date '+%s'`"
